[project]
name = 'Memetic-Evolution-Simulator'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.meme-nft]
path = 'contracts/meme-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.meme-token]
path = 'contracts/meme-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
